### ISSUE TITLE
show container for switches

### ISSUE THREAD

**Issue by Yasharah** [lrupp/racktables-reports#1]
Hello,
thank you for rewriting the plugin. I have one question: is there an easy way to show the container for switches, the same way they are shown for servers in the location column? I was able to do this myself for the old plugin, but my "programming skills" don't help me with yours.

greetings
Yoshi

**Comment by lrupp** [comment]
I'm unsure if I understand you right, as this should be included in the code already.

![Racktables_SwitchReport_for_switch_in_cassis](https://user-images.githubusercontent.com/3956279/56287560-fcd05100-611c-11e9-842c-cbaf18fcdd1f.png)

If you can paste your changes in the old plugin here, I can try to integrate them in the new code.

**Comment by lrupp** [comment]
Closing: 
- question not answered after 3 months
- issue works for me
